"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
import {parseLegacyCsv,type CsvPreview} from "../../lib/csv-import";
type Player={id:string;name:string;active:boolean};type Session={id:string;date:string;name:string};
const normalize=(value:string)=>value.replace(/\s+/g," ").trim();
export default function ImportPage(){const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<CsvPreview|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[signed,setSigned]=useState(false),[signedEmail,setSignedEmail]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState("");const inspect=async(f:File)=>{setFile(f);setStatus("");setPreview(parseLegacyCsv(await f.text()))};useEffect(()=>{supabase?.auth.getUser().then(({data,error})=>{setSigned(!error&&!!data.user);setSignedEmail(data.user?.email??"")})},[]);const login=async()=>{if(!supabase)return;setBusy(true);await supabase.auth.signOut({scope:"local"});const{data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error||!data.session||!data.user){setSigned(false);setStatus(`登录失败：${error?.message??"未能建立登录会话"}`);return}setSigned(true);setSignedEmail(data.user.email??email.trim());setStatus("✓ 管理员已登录，请继续选择 CSV")};
 const run=async()=>{if(!supabase||!file||!preview||preview.errors.length)return;setBusy(true);setStatus("正在检查管理员身份…");try{const{data:sessionData,error:sessionError}=await supabase.auth.getSession();if(sessionError||!sessionData.session){setSigned(false);throw new Error("登录状态已过期，请在本页重新登录")};const{data:auth,error:authError}=await supabase.auth.getUser(sessionData.session.access_token);if(authError||!auth.user){setSigned(false);throw new Error("登录验证失败，请在本页重新登录")};setSignedEmail(auth.user.email??"");
 setStatus("正在匹配玩家…");const{data:existingPlayers,error:playersError}=await supabase.from("players").select("id,name,active");if(playersError)throw playersError;const playerMap=new Map((existingPlayers??[]).map((p:Player)=>[normalize(p.name),p]));const missing=preview.players.filter(name=>!playerMap.has(normalize(name)));const activeCount=(existingPlayers??[]).filter((p:Player)=>p.active).length;if(activeCount+missing.length>20)throw new Error(`导入后 active 玩家会超过 20 人；当前 ${activeCount} 人，新增 ${missing.length} 人`);if(missing.length){const{data:created,error}=await supabase.from("players").insert(missing.map(name=>({name,active:true}))).select("id,name,active");if(error)throw error;(created??[]).forEach((p:Player)=>playerMap.set(normalize(p.name),p))}
 setStatus("正在建立历史活动…");const{data:existingSessions,error:sessionsError}=await supabase.from("sessions").select("id,date,name").in("date",preview.dates);if(sessionsError)throw sessionsError;const sessionMap=new Map((existingSessions??[]).filter((s:Session)=>s.name==="历史导入").map((s:Session)=>[s.date,s]));const missingDates=preview.dates.filter(date=>!sessionMap.has(date));if(missingDates.length){const{data:created,error}=await supabase.from("sessions").insert(missingDates.map(date=>({date,name:"历史导入",notes:`来源：${file.name}`}))).select("id,date,name");if(error)throw error;(created??[]).forEach((s:Session)=>sessionMap.set(s.date,s))}
 setStatus("正在生成独立对局…");const prefix=`legacy-csv:${file.name}:`;const{data:existingGames,error:existingError}=await supabase.from("games").select("notes").like("notes",`${prefix}%`);if(existingError)throw existingError;const existingNotes=new Set((existingGames??[]).map(x=>x.notes));const games:Record<string,unknown>[]=[];for(const row of preview.rows){const a=playerMap.get(normalize(row.playerA))!,b=playerMap.get(normalize(row.playerB))!,session=sessionMap.get(row.date)!;for(let i=1;i<=row.aWins;i++){const notes=`${prefix}${row.line}:A:${i}`;if(!existingNotes.has(notes))games.push({session_id:session.id,player_a_id:a.id,player_b_id:b.id,player_a_balls:null,player_b_balls:null,finish_type:"legacy_unknown",black_ball_foul_player_id:null,winner_id:a.id,loser_id:b.id,table_balls_remaining:null,is_legacy_import:true,notes})}for(let i=1;i<=row.bWins;i++){const notes=`${prefix}${row.line}:B:${i}`;if(!existingNotes.has(notes))games.push({session_id:session.id,player_a_id:a.id,player_b_id:b.id,player_a_balls:null,player_b_balls:null,finish_type:"legacy_unknown",black_ball_foul_player_id:null,winner_id:b.id,loser_id:a.id,table_balls_remaining:null,is_legacy_import:true,notes})}}
 for(let offset=0;offset<games.length;offset+=100){setStatus(`正在写入对局 ${Math.min(offset+100,games.length)} / ${games.length}…`);const{error}=await supabase.from("games").insert(games.slice(offset,offset+100));if(error)throw error}
 const{count,error:verifyError}=await supabase.from("games").select("id",{count:"exact",head:true}).like("notes",`${prefix}%`);if(verifyError)throw verifyError;if(count!==preview.games)throw new Error(`核对失败：预期 ${preview.games} 局，数据库中为 ${count} 局`);setStatus(`✓ 导入完成：${preview.players.length} 位玩家、${preview.dates.length} 个活动日期、${count} 局比赛`)}catch(error){setStatus(`导入失败：${error instanceof Error?error.message:"未知错误"}`)}finally{setBusy(false)}};
 if(!signed)return <main><section className="screen"><p className="eyebrow">一步完成导入</p><h1>管理员登录</h1><div className="form-card"><label>邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy||!email||!password} onClick={login}>{busy?"正在登录…":"登录并继续导入"}</button></div>{status&&<p className="notice">{status}</p>}</section></main>;
 return <main><section className="screen"><header><div><p className="eyebrow">管理员工具 · {signedEmail}</p><h1>CSV 历史导入</h1></div><button className="back" onClick={async()=>{await supabase?.auth.signOut({scope:"local"});setSigned(false);setSignedEmail("");setStatus("请重新登录")}}>↻</button></header><div className="form-card"><label>选择 CSV<input type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/></label></div>{preview&&<><h2>导入预览</h2><div className="metrics"><div><strong>{preview.rows.length}</strong><span>中八汇总行</span></div><div><strong>{preview.games}</strong><span>独立对局</span></div><div><strong>{preview.players.length}</strong><span>玩家</span></div></div><div className="card"><p>活动日期：{preview.dates.length} 天</p><p>范围：{preview.dates[0]} 至 {preview.dates.at(-1)}</p><p>跳过其他类型：{preview.skipped.length} 行</p>{preview.errors.map(error=><p className="notice" key={error}>{error}</p>)}</div><button className="primary" disabled={busy||!!preview.errors.length} onClick={run}>{busy?"正在导入…":"确认写入 Supabase"}</button></>}{status&&<p className="notice">{status}</p>}</section></main>}
