"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { determineGameResult, type FinishType } from "../../lib/game-rules";
type Player={id:string;name:string;active:boolean}; type Session={id:string;name:string;date:string};
const finishes:Record<FinishType,string>={normal:"正常抢8结束",early_black:"提前打进黑八直接判负",wrong_pocket:"黑八进错袋直接判负",scratch_on_black:"击打黑八时白球落袋",other_black_foul:"其他黑八犯规",legacy_unknown:"历史未知"};
export default function Setup(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[signed,setSigned]=useState(false),[players,setPlayers]=useState<Player[]>([]),[sessions,setSessions]=useState<Session[]>([]),[message,setMessage]=useState(""),[playerName,setPlayerName]=useState(""),[sessionName,setSessionName]=useState("晚场台球"),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [game,setGame]=useState({session:"",a:"",b:"",aBalls:8,bBalls:4,finish:"normal" as FinishType,foul:""});
 const load=async()=>{if(!supabase)return;const [{data:p},{data:s},{data:auth}]=await Promise.all([supabase.from("players").select("id,name,active").eq("active",true).order("name"),supabase.from("sessions").select("id,name,date").order("date",{ascending:false}),supabase.auth.getSession()]);setPlayers(p??[]);setSessions(s??[]);setSigned(!!auth.session);if(p?.length)setGame(g=>({...g,a:g.a||p[0].id,b:g.b||p[1]?.id||"",foul:g.foul||p[0].id}));if(s?.[0])setGame(g=>({...g,session:g.session||s[0].id}));};
 useEffect(()=>{load()},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?`登录失败：${error.message}`:"登录成功");await load()};
 const createPlayer=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!playerName.trim())return;const {error}=await supabase.from("players").insert({name:playerName.trim()});setMessage(error?`无法新增玩家：${error.message}`:`已新增 ${playerName}`);setPlayerName("");await load()};
 const createSession=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const {error}=await supabase.from("sessions").insert({date,name:sessionName});setMessage(error?`无法新建活动：${error.message}`:"活动已创建");await load()};
 const saveGame=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;try{const r=determineGameResult({playerAId:game.a,playerBId:game.b,playerABalls:game.aBalls,playerBBalls:game.bBalls,finishType:game.finish,foulPlayerId:game.finish==="normal"?null:game.foul});const {error}=await supabase.from("games").insert({session_id:game.session,player_a_id:game.a,player_b_id:game.b,player_a_balls:game.aBalls,player_b_balls:game.bBalls,finish_type:game.finish,black_ball_foul_player_id:game.finish==="normal"?null:game.foul,winner_id:r.winnerId,loser_id:r.loserId,table_balls_remaining:r.tableBallsRemaining});setMessage(error?`无法保存对局：${error.message}`:`✓ 已保存，对局胜者：${players.find(x=>x.id===r.winnerId)?.name}`)}catch(err){setMessage(err instanceof Error?err.message:"请检查输入")}};
 if(!supabase)return <main><section className="screen"><h1>尚未配置 Supabase</h1></section></main>;
 if(!signed)return <main><section className="screen"><p className="eyebrow">安全登录</p><h1>登录团建助手</h1><form className="form-card" onSubmit={login}><label>邮箱<input value={email} type="email" onChange={e=>setEmail(e.target.value)} required/></label><label>密码<input value={password} type="password" onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">登录</button>{message&&<p className="notice">{message}</p>}</form></section></main>;
 return <main><section className="screen"><header><div><p className="eyebrow">已连接 Supabase</p><h1>真实数据管理</h1></div><a className="back" href="/">⌂</a></header>{message&&<p className="notice">{message}</p>}<h2>玩家</h2><form className="form-card" onSubmit={createPlayer}><label>新增玩家<input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="例如：玩家小王"/></label><button className="primary">新增玩家</button></form><p className="helper">现有玩家：{players.map(p=>p.name).join("、")||"尚无"}</p><h2>团建活动</h2><form className="form-card" onSubmit={createSession}><label>日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>活动名称<input value={sessionName} onChange={e=>setSessionName(e.target.value)}/></label><button className="primary">新建活动</button></form><h2>真实记一局</h2><form className="form-card" onSubmit={saveGame}><label>活动<Select value={game.session} items={sessions.map(x=>[x.id,`${x.date} · ${x.name}`])} change={v=>setGame({...game,session:v})}/></label><label>玩家 A<Select value={game.a} items={players.map(x=>[x.id,x.name])} change={v=>setGame({...game,a:v})}/></label><label>玩家 B<Select value={game.b} items={players.map(x=>[x.id,x.name])} change={v=>setGame({...game,b:v})}/></label><div className="scores"><Count title="A 进球数" value={game.aBalls} change={v=>setGame({...game,aBalls:v})}/><Count title="B 进球数" value={game.bBalls} change={v=>setGame({...game,bBalls:v})}/></div><label>结束方式<Select value={game.finish} items={Object.entries(finishes).filter(([k])=>k!=="legacy_unknown")} change={v=>setGame({...game,finish:v as FinishType})}/></label>{game.finish!=="normal"&&<label>犯规玩家<Select value={game.foul} items={players.filter(x=>x.id===game.a||x.id===game.b).map(x=>[x.id,x.name])} change={v=>setGame({...game,foul:v})}/></label>}<button className="primary" disabled={!game.session||!game.a||!game.b}>保存这一局</button></form></section></main>;
}
function Select({value,items,change}:{value:string;items:string[][];change:(v:string)=>void}){return <select value={value} onChange={e=>change(e.target.value)}><option value="">请选择</option>{items.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>};function Count({title,value,change}:{title:string;value:number;change:(v:number)=>void}){return <div className="counter"><small>{title}</small><div><button type="button" onClick={()=>change(Math.max(0,value-1))}>−</button><b>{value}</b><button type="button" onClick={()=>change(Math.min(8,value+1))}>＋</button></div></div>}
