export type GameRecord={id:string;session_id:string;player_a_id:string;player_b_id:string;winner_id:string;loser_id:string};
export type PlayerStat={playerId:string;games:number;wins:number;losses:number;winRate:number};
export function calculatePlayerStats(players:{id:string}[],games:GameRecord[]):PlayerStat[]{return players.map(player=>{const gamesFor=games.filter(g=>g.player_a_id===player.id||g.player_b_id===player.id);const wins=gamesFor.filter(g=>g.winner_id===player.id).length;return{playerId:player.id,games:gamesFor.length,wins,losses:gamesFor.length-wins,winRate:gamesFor.length?wins/gamesFor.length:0}})}
export function calculateMvp(players:{id:string}[],games:GameRecord[],minimum=6){const eligible=calculatePlayerStats(players,games).filter(x=>x.games>=minimum);const rate=Math.max(...eligible.map(x=>x.winRate),-1);return eligible.filter(x=>x.winRate===rate)}
export function calculateHeadToHead(a:string,b:string,games:GameRecord[]){const pair=games.filter(g=>(g.player_a_id===a&&g.player_b_id===b)||(g.player_a_id===b&&g.player_b_id===a));const aWins=pair.filter(g=>g.winner_id===a).length;return{games:pair.length,aWins,bWins:pair.length-aWins}}
export type Expense={id:string;session_id:string;category:string;amount_cents:number};export type Payment={expense_id:string;payer_id:string;amount_cents:number};export type Participant={expense_id:string;player_id:string};
function allocateCentsByWeight(amountCents:number,weights:Map<string,number>){const totalWeight=[...weights.values()].reduce((sum,weight)=>sum+weight,0);if(!totalWeight)return new Map<string,number>();const rows=[...weights].map(([id,weight],index)=>{const numerator=amountCents*weight;return{id,index,share:Math.floor(numerator/totalWeight),remainder:numerator%totalWeight}});let centsLeft=amountCents-rows.reduce((sum,row)=>sum+row.share,0);rows.sort((a,b)=>b.remainder-a.remainder||a.index-b.index);for(let i=0;i<centsLeft;i++)rows[i%rows.length].share++;return new Map(rows.map(row=>[row.id,row.share]))}
export function calculateExpenseBalances(players:{id:string}[],games:GameRecord[],expenses:Expense[],participants:Participant[],payments:Payment[]){const cents=new Map(players.map(p=>[p.id,0]));for(const expense of expenses){const paid=payments.filter(x=>x.expense_id===expense.id);for(const x of paid)cents.set(x.payer_id,(cents.get(x.payer_id)||0)+x.amount_cents);let shares:Map<string,number>=new Map();if(expense.category==="pool"){const joins=games.filter(g=>g.session_id===expense.session_id).flatMap(g=>[g.player_a_id,g.player_b_id]);const weights=new Map<string,number>();for(const id of joins)weights.set(id,(weights.get(id)||0)+1);shares=allocateCentsByWeight(expense.amount_cents,weights)}else{const ids=participants.filter(x=>x.expense_id===expense.id).map(x=>x.player_id);ids.forEach((id,i)=>shares.set(id,Math.floor(expense.amount_cents/ids.length)+(i<expense.amount_cents%ids.length?1:0)))}for(const[id,share]of shares)cents.set(id,(cents.get(id)||0)-share)}return [...cents].map(([playerId,value])=>({playerId,cents:value}))}
export function calculateSettlement(balances:{playerId:string;cents:number}[]){const debtors=balances.filter(x=>x.cents<0).map(x=>({...x,cents:-x.cents})),creditors=balances.filter(x=>x.cents>0).map(x=>({...x}));const result:{from:string;to:string;cents:number}[]=[];let d=0,c=0;while(d<debtors.length&&c<creditors.length){const cents=Math.min(debtors[d].cents,creditors[c].cents);result.push({from:debtors[d].playerId,to:creditors[c].playerId,cents});debtors[d].cents-=cents;creditors[c].cents-=cents;if(!debtors[d].cents)d++;if(!creditors[c].cents)c++}return result}
